server:
  port: 9702

#spring
spring:
  profiles:
    active: test

  redis:
    database: 0
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 12341234
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # 连接池中的最大/小空闲连接
        max-idle: 8
        min-idle: 5
    # 连接超时时间（毫秒）
    timeout: 3000




